spring:
  application:
    name: SampleSF

mvf4ms:
  version: 4.2.1
  dependencies:
    - name: dependency1
      dependence:
        - id: pay
          function: pay
          slas:
            - 2
        - id: navigation
          function: navigation
          slas:
            - 3
            - 4

server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://{REGISTRY_IP}:{REGISTRY_PORT}/eureka
